GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYnJ1bm8iLCJpYXQiOjE2MzEwMjc4MzJ9.i2wA3Kos8TejdH6MN3PUZFjVmNOV9jvr_eCQaweLIcg
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "bruno"
}